### ISSUE TITLE
theme rider error

### ISSUE THREAD

**Issue by x0rld** [oh-my-fish/packages-main#135]
I just install the theme rider as you can see in the screenshot but there is a weird char and gnome say " we canno't find the font "
![image](https://user-images.githubusercontent.com/45242856/103875065-3c4d8680-50d2-11eb-98be-05068ed9fd84.png)

**Comment by oranja** [comment]
Seems like you need to install a [Powerline font](https://github.com/powerline/fonts) or a [Nerd font](https://github.com/ryanoasis/nerd-fonts) and make your terminal use it.

But really this issue belong more to the *rider* theme's [repo](https://github.com/rideron89/rider-theme/issues/new).

**Comment by x0rld** [comment]
ok thx
I didn't found the repo
