### ISSUE TITLE
fatal: couldn't find remote ref refs/heads/master

### ISSUE THREAD

**Issue by TruncatedDinosour** [oh-my-fish/packages-main#145]
i tried instaling "colored-man-pages" and i get this error while updating
```
╭─ ari at ari-arch in ~
╰> omf update 
Oh My Fish is up to date.
You are now using Oh My Fish version 7.
Updating https://github.com/oh-my-fish/packages-main master... Done!
archlinux is already up-to-date.
fatal: couldn't find remote ref refs/heads/master
Could not update colored_man_pages.fish.
default is already up-to-date.
```

**Comment by faho** [comment]
You've updated fish to 3.3.0, which turns off the long-deprecated `^foo` redirection. One of your packages is still using it, check `grep -r '\^[/&]' ~/.config/fish/`.

Also this is the entirely wrong repository to report this in.
