### ISSUE TITLE
Powerline is installed but still does not work 

### ISSUE THREAD

**Issue by MrMic** [oh-my-fish/packages-main#163]
Hi,

I am on Ubuntu 20.04 and have installed powerline with apt,
and installed the required fonts! But the prompt still displays:
"Please install powerline" => But it is installed

Cannot git status/branch in my prompt ...

Can you fix it ?

**Comment by scorphus** [comment]
Can you please report this issue in [plugin-powerline](/iamruinous/plugin-powerline), that is the correct repository for the plugin. Thanks!
