### ISSUE TITLE
git-refresh uses ":" instead of "=" in the package definition file

### ISSUE THREAD

**Issue by emarsk** [oh-my-fish/packages-main#97]
The title is pretty much self-explanatory.
Are ":"'s allowed syntax? Even then, git-refresh is the only one that uses them.
I'm building an html page for myself with the list of omf plugins, and git-refresh brings a hiccup in the parsing.

**Comment by bobthecow** [comment]
No, it is not supported. You'll notice OMF doesn't know about git-refresh :-/ 

<img width="762" alt="Screen Shot 2019-09-14 at 8 12 53 AM" src="https://user-images.githubusercontent.com/53660/64910016-8170cc80-d6c7-11e9-9f55-cf1b9ed79923.png">
